/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import java.util.ArrayList;
import java.util.List;

public class AppTest {
    @Test
    public void test() {
        List<FiniteStateAutomaton> dfsas = new ArrayList<>();
        dfsas.add(new FiniteStateAutomaton(true, IdentifierToken::new) {
            @Override
            public boolean accepts(String input) {
                if (!Character.isLetter(input.charAt(0))) {
                    return false;
                }

                for (int i = 1; i < input.length() - 1; i++) {
                    if (!Character.isLetterOrDigit(input.charAt(i))) {
                        return false;
                    }
                }

                return !Character.isLetterOrDigit(input.charAt(input.length() - 1));
            }
        });
        dfsas.add(new FiniteStateAutomaton(true, NumberToken::new) {
            @Override
            public boolean accepts(String input) {
                if (!Character.isDigit(input.charAt(0))) {
                    return false;
                }

                for (int i = 1; i < input.length() - 1; i++) {
                    if (!Character.isLetterOrDigit(input.charAt(i))) {
                        return false;
                    }
                }

                return !Character.isLetterOrDigit(input.charAt(input.length() - 1));
            }
        });

        Scanner scanner = new Scanner("niki0 2e10", dfsas);
        while (scanner.hasNext()) {
            Token next = scanner.next();
            System.out.println(next);
        }
    }
}
