/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;

import java.util.Arrays;


public class AppTest {
    private FiniteStateAutomaton identifierAutomaton = new FiniteStateAutomaton(true, IdentifierToken::new) {
        @Override
        public boolean accepts(String input) {
            if (!Character.isLetter(input.charAt(0))) {
                return false;
            }

            for (int i = 1; i < input.length() - 1; i++) {
                if (!Character.isLetterOrDigit(input.charAt(i))) {
                    return false;
                }
            }

            return !Character.isLetterOrDigit(input.charAt(input.length() - 1));
        }
    };

    private FiniteStateAutomaton numberAutomaton = new FiniteStateAutomaton(true, NumberToken::new) {
        @Override
        public boolean accepts(String input) {
            if (!Character.isDigit(input.charAt(0))) {
                return false;
            }

            for (int i = 1; i < input.length() - 1; i++) {
                if (!Character.isLetterOrDigit(input.charAt(i))) {
                    return false;
                }
            }

            return !Character.isLetterOrDigit(input.charAt(input.length() - 1));
        }
    };

    @Test
    public void test() {
        Scanner scanner = new Scanner("cutieNiki 2e10", Arrays.asList(identifierAutomaton, numberAutomaton));
        while (scanner.hasNext()) {
            Token next = scanner.next();
            System.out.println(next);
        }
    }
}
